export const ConfigActions = {

  // Toggle theme
  TOGGLE_THEME: 'TOGGLE_THEME',
  // Sidenav Left
  OPEN_SIDENAV_LEFT: 'OPEN_SIDENAV',
  CLOSE_SIDENAV_LEFT: 'CLOSE_SIDENAV_LEFT',
  TOGGLE_SIDENAV_LEFT: 'TOGGLE_SIDENAV_LEFT',
  CLOSE_SIDENAV_LEFT_IF_MOBILE: 'CLOSE_SIDENAV_IF_MOBILE',
  // Sidenav Right
  OPEN_SIDENAV_RIGHT: 'OPEN_SIDENAV_RIGHT',
  CLOSE_SIDENAV_RIGHT: 'CLOSE_SIDENAV_RIGHT',
  TOGGLE_SIDENAV_RIGHT: 'TOGGLE_SIDENAV_RIGHT',
  CLOSE_SIDENAV_RIGHT_IF_MOBILE: 'CLOSE_SIDENAV_IF_MOBILE',

  SET_SIDENAV_MODE: 'SET_SIDENAV_MODE'
};
