export const ConfigActions = {
  TOGGLE_THEME: 'TOGGLE_THEME',
  TOGGLE_SIDENAV: 'TOGGLE_SIDENAV',
  CLOSE_SIDENAV: 'CLOSE_SIDENAV',
  CLOSE_SIDENAV_IF_MOBILE: 'CLOSE_SIDENAV_IF_MOBILE',
  OPEN_SIDENAV: 'OPEN_SIDENAV',
  SET_SIDENAV_MODE: 'SET_SIDENAV_MODE'
};
