export const NavigationActions = {
  // Marker
  REMOVE_MARKER: 'REMOVE_MARKER',
  REMOVE_MARKER_SUCCESS: 'REMOVE_MARKER_SUCCESS',
  REMOVE_MARKER_FAILED: 'REMOVE_MARKER_FAILED',

  FETCH_MARKER: 'FETCH_MARKER',
  FETCH_MARKER_SUCCESS: 'FETCH_MARKER_SUCCESS',
  FETCH_MARKER_FAILED: 'FETCH_MARKER_FAILED'
}
