export const NavigationActions = {
  // Marker
  ADD_MARKER_SUCCESS: 'ADD_MARKER_SUCCESS',
  ADD_MARKER_FAILED: 'ADD_MARKER_FAILED',

  REMOVE_MARKER: 'REMOVE_MARKER',
  REMOVE_MARKER_SUCCESS: 'REMOVE_MARKER_SUCCESS',
  REMOVE_MARKER_FAILED: 'REMOVE_MARKER_FAILED',

  FETCH_MARKER_DETAILS: 'FETCH_MARKER_DETAILS',
  FETCH_MARKER_DETAILS_SUCCESS: 'FETCH_MARKER_DETAILS_SUCCESS',
  FETCH_MARKER_DETAILS_FAILED: 'FETCH_MARKER_DETAILS_FAILED',
}
