export const UserActions = {
  USR_IS_CONNECTING: 'USR_IS_CONNECTING',
  USR_IS_CONNECTED: 'USR_IS_CONNECTED',
  USR_IS_DISCONNECTING: 'USR_IS_DISCONNECTING',
  USR_IS_DISCONNECTED: 'USR_IS_DISCONNECTED',
  USR_CONNECTION_FAILED: 'USR_CONNECTION_FAILED',
  USR_DISCONNECTION_FAILED: 'USR_DISCONNECTION_FAILED'
};
