export const UserActions = {
  // User Connection
  USR_IS_CONNECTING: 'USR_IS_CONNECTING',
  USR_IS_CONNECTED: 'USR_IS_CONNECTED',
  USR_IS_DISCONNECTING: 'USR_IS_DISCONNECTING',
  USR_IS_DISCONNECTED: 'USR_IS_DISCONNECTED',
  USR_CONNECTION_FAILED: 'USR_CONNECTION_FAILED',
  USR_DISCONNECTION_FAILED: 'USR_DISCONNECTION_FAILED',

  // User Registeration
  USR_IS_REGISTERING: 'USR_IS_REGISTERING',
  USR_IS_REGISTERED: 'USR_IS_REGISTERED',
  USR_REGISTERATION_FAILED: 'USR_REGISTERATION_FAILED'
};
